name: Docker

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build_and_push_to_gcp_and_deploy_to_cloud_run:
    runs-on: ubuntu-latest
    
    container: 
      image: google/cloud-sdk:latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Check commit sha ...
      run: echo ${{ github.sha }}
      
    - name: Authenticate into Google Cloud Platform
      run: gcloud auth activate-service-account kanoon@react-101-325014.iam.gserviceaccount.com --key-file=key.json
      
    - name: Configure Docker to use Google Cloud Platform
      run: gcloud auth configure-docker
    
    - name: set project id in gcloud
      run: gcloud config set project react-101-325014

    - name: Push image to Google Cloud Container Registry
      run: gcloud builds submit --tag gcr.io/react-101-325014/react

    - name: Deploy to Cloud Run
      run: gcloud beta run deploy react-101--quiet --image gcr.io/react-101-325014/react:latest --project react-101-325014 --region asia-southeast1 --platform managed
